name: Issue
description: Create a feature request, bug report, or task
labels: []
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Feature
        - Bug
        - Chore
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature, bug, or task
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How do we know this is done?
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false
